name: Deploy Production

#run the job to server when pull request is closed
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-18.04
    steps:
      - name: deploy (run container), with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls .
            source ~/.bash_profile
            cd blog_app
            ls .
            git pull origin main
            cd backend
            php -v
            composer install
            cp .env.production .env
            php artisan key:generate --force
            docker-compose exec -T app php artisan migrate --force
            docker-compose exec web npm run deploy
